<?php

return array(

    'title'                 => '项目名称',
    'action_type_name'      => '行动方式',
    'service_object_name'   => '服务对象',
    'type_name'             => '服务内容',
    'type'                  => '服务内容',
    'project_sub_type'      => '项目专题',
    'manager_name'          => '项目官员',
    'partner_title'         => '机构名称',
    'service_area'          => '机构/社区名称',
    'other_partner_title'   => '联合资助伙伴',
    'contact_name'          => '负责人',
    'contact_name_short'    => '负责人',
    'partner_leader_name'   => '负责人',
    'partner_leader_email'  => '负责人邮箱',
    'partner_leader_mobile' => '负责人手机',
    'status_name'           => '项目状态',
    'project_address'       => '项目地点',
    'address'               => '项目实施地',
    'partner_title'         => '申请机构',
    'actual_end_time'       => '实际结项时间',
    'total_budget'          => '项目预算',
    'have_budget'           => '自筹资金',
    'have_budget_source'    => '自筹资金来源',
    'need_budget'           => '申请资金',
    'contract_budget'       => '合同金额',
    'contract_related'      => '合同情况',
    'APPLY_TIME'            => '申请时间',
    'AUDIT_TIME'            => '项目复审时间',
    'CURRENT_TIME'          => '当前时间',
    'start_time'            => '项目开始时间',
    'end_time'              => '项目结束时间',
    'contract_time'         => '签订合同时间',
    'INTERIM_REPORT_TIME'   => '中期报告时间',
    'FINAL_REPORT_TIME'     => '末期报告时间',
    'FINAL_AUDIT_TIME'      => '末期审计时间',
    'FINAL_WRAPUP_TIME'     => '总结评议时间',
    'delay_one_time'        => '第一次延期',
    'delay_two_time'        => '第二次延期',    
    'basic_info'            => '项目基本信息',
    'grant_time_1'          => '拨款1',
    'grant_time_2'          => '拨款2',
    'grant_time_3'          => '拨款3',
    'grant_time_4'          => '拨款4',
    'grant_time_5'          => '拨款5',
    'interim_report_file'   => '中期报告文件',
    'final_report_file'     => '末期报告文件',
    'HAS_GRANT_AMOUNT'     => '已资助',
    'contract_amount'     => '合同额',
    'file_system_link'     => '文件系统连接',
    'GRANT_AMOUNT_RATIO'     => '已资助',

);

?>